from __future__ import annotations

import unittest

from minidora.hds_compiler_v1 import 公開HDSコンパイラ


class HDS関係補完試験(unittest.TestCase):
    def setUp(self) -> None:
        self.compiler = 公開HDSコンパイラ()

    @staticmethod
    def _edges(ir, kind: str) -> set[tuple[str, str]]:
        coords = ir.座標辞書()
        result: set[tuple[str, str]] = set()
        for relation in ir.関係:
            if relation.種別 != kind or len(relation.始点) != 1 or len(relation.終点) != 1:
                continue
            start = coords.get(relation.始点[0])
            end = coords.get(relation.終点[0])
            if start is not None and end is not None:
                result.add((str(start.内容), str(end.内容)))
        return result

    def test_科学文の結合符号化局在を明示関係へ射影する(self) -> None:
        cases = (
            ("Protein A binds to Protein B.", "結合", ("Protein A", "Protein B")),
            ("Gene A encodes Protein B.", "符号化", ("Gene A", "Protein B")),
            ("Protein A localizes to the nucleus.", "局在", ("Protein A", "the nucleus")),
        )
        for text, kind, expected in cases:
            with self.subTest(text=text):
                ir = self.compiler.コンパイル(text)
                self.assertIn(expected, self._edges(ir, kind))

    def test_受動態を能動態と同じ方向へ正規化する(self) -> None:
        cases = (
            ("Target protein is inhibited by Regulator X.", "阻害", ("Regulator X", "Target protein")),
            ("Product Y is generated by Enzyme Z.", "生成", ("Enzyme Z", "Product Y")),
            ("Protein B is encoded by Gene A.", "符号化", ("Gene A", "Protein B")),
            ("Factor A is required for Process B.", "要求", ("Process B", "Factor A")),
        )
        for text, kind, expected in cases:
            with self.subTest(text=text):
                ir = self.compiler.コンパイル(text)
                self.assertIn(expected, self._edges(ir, kind))

    def test_否定文を肯定関係へ誤昇格しない(self) -> None:
        ir = self.compiler.コンパイル("Protein A does not bind to Protein B.")
        self.assertNotIn(("Protein A does not", "Protein B"), self._edges(ir, "結合"))
        self.assertFalse(self._edges(ir, "結合"))

    def test_疑問の未知端点を実体へ誤固定しない(self) -> None:
        ir = self.compiler.コンパイル("Which protein binds to Protein B?")
        self.assertFalse(self._edges(ir, "結合"))

    def test_既存関係を重複追加しない(self) -> None:
        ir = self.compiler.コンパイル("Protein A causes apoptosis.")
        edges = self._edges(ir, "因果")
        self.assertEqual(edges, {("Protein A", "apoptosis")})


if __name__ == "__main__":
    unittest.main()
