use_default_settings: true

general:
  instance_name: "MINIDORA Local Search"

search:
  safe_search: 0
  formats:
    - html
    - json

server:
  limiter: false
  public_instance: false
  image_proxy: false
