const messagesEl=document.querySelector('#messages');const form=document.querySelector('#composer');const input=document.querySelector('#input');const send=document.querySelector('#send');const health=document.querySelector('#health');const traceEmpty=document.querySelector('#traceEmpty');const traceBody=document.querySelector('#traceBody');
let session=localStorage.getItem('minidora_session')||crypto.randomUUID();localStorage.setItem('minidora_session',session);let busy=false;
function welcome(){messagesEl.innerHTML=`<div class="welcome"><h1>MINIDORA</h1><p>非ニューラルLLM Coreに、交換可能な能力Moduleを接続した製品版プロトタイプです。<br>回答の理由は後付け生成ではなく、実行経路そのものをTraceとして確認できます。</p><div class="chips"><button class="chip">今日のニュースは？</button><button class="chip">何ができる？</button><button class="chip">(12+8)*3</button></div></div>`;messagesEl.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{input.value=b.textContent;input.focus()})}
welcome();
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(u){try{const x=new URL(String(u||''),location.origin);return /^https?:$/.test(x.protocol)?x.href:''}catch{return ''}}
function add(role,text,data){const w=document.createElement('div');w.className='msg '+role;const src=(data?.sources||[]).map(s=>{const href=safeUrl(s.URL);return `<div class="source">${esc(s.出典||s.source||'source')} — ${href?`<a target="_blank" rel="noreferrer" href="${esc(href)}">${esc(s.題名||s.title)}</a>`:esc(s.題名||s.title)}</div>`}).join('');w.innerHTML=`<div class="bubble">${esc(text)}${role==='assistant'&&data?`<div class="meta"><span>${esc(data.route||'')}</span><span>${esc(data.status||'')}</span><button data-trace="${esc(data.trace_id||'')}">Trace</button></div>${src?`<div class="sources">${src}</div>`:''}`:''}</div>`;messagesEl.querySelector('.welcome')?.remove();messagesEl.appendChild(w);w.querySelector('[data-trace]')?.addEventListener('click',()=>loadTrace(data.trace_id));messagesEl.scrollTop=messagesEl.scrollHeight}
async function loadTrace(id){if(!id)return;traceEmpty.classList.add('hidden');traceBody.classList.remove('hidden');traceBody.innerHTML='<div class="trace-empty">Trace読み込み中...</div>';try{const r=await fetch('/api/trace/'+id);const d=await r.json();if(!r.ok)throw new Error(d.error||r.status);const t=d.trace;const events=(t['イベント']||[]).map(e=>`<div class="event"><div class="title">${esc(e['番号'])}. ${esc(e['段階'])}</div><div class="sub">${esc(e['モジュール'])} / ${esc(e['版'])}</div><pre>${esc(JSON.stringify({input:e['入力'],output:e['出力'],evidence:e['根拠']},null,2))}</pre></div>`).join('');traceBody.innerHTML=`<div class="kv"><div class="k">検証</div><div>${d.valid?'✓ hash chain valid':'✕ invalid'}</div><div class="k">経路</div><div>${esc(t['経路'])}</div><div class="k">状態</div><div>${esc(t['状態'])}</div><div class="k">Trace ID</div><div class="hash">${esc(t['追跡ID'])}</div><div class="k">Root hash</div><div class="hash">${esc(t['ルートハッシュ'])}</div><div class="k">前応答hash</div><div class="hash">${esc(t['前応答ハッシュ']||'—')}</div></div>${events}`;}catch(e){traceBody.innerHTML=`<div class="trace-empty">Trace取得失敗: ${esc(e.message)}</div>`}}
async function submit(text){if(busy||!text.trim())return;busy=true;send.disabled=true;add('user',text);input.value='';try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:session,message:text})});const d=await r.json();if(!r.ok)throw new Error(d.error||r.status);add('assistant',d.response,d);loadTrace(d.trace_id)}catch(e){add('assistant','接続または処理に失敗しました: '+e.message)}finally{busy=false;send.disabled=false;input.focus()}}
form.addEventListener('submit',e=>{e.preventDefault();submit(input.value)});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px'});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});document.querySelector('#newSession').onclick=()=>{session=crypto.randomUUID();localStorage.setItem('minidora_session',session);welcome();traceBody.classList.add('hidden');traceEmpty.classList.remove('hidden')};
fetch('/health').then(r=>r.json()).then(()=>{health.textContent='接続済み';health.classList.add('ok')}).catch(()=>{health.textContent='未接続';health.classList.add('bad')});
